# Generated by Django 4.0.5 on 2023-05-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='STATE',
        ),
    ]
