# Generated by Django 4.0.5 on 2023-05-31 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0003_remove_profile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeactivationUser_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('validation', models.BooleanField(default=False)),
                ('validation_date', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='DeactivationUser_Request_Created_by', to=settings.AUTH_USER_MODEL)),
                ('id_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validation_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='DeactivationUser_Request_Validated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
