# Generated by Django 4.0.5 on 2023-06-01 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0005_restoreuser_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Type', models.CharField(choices=[('Administrador', 'Administrador'), ('Trabajador', 'Trabajador')], max_length=15, null=True)),
                ('code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('invitation_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('validation_date', models.DateTimeField(default=None, null=True)),
                ('User_sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validation_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Invitation_Validated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
