# Generated by Django 4.0.5 on 2023-06-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invitation_Date',
            new_name='created_date',
        ),
    ]
