# Generated by Django 4.0.5 on 2023-05-03 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=20, unique=True)),
                ('Description', models.CharField(max_length=70)),
                ('classification', models.CharField(choices=[('Ejercicio', 'Ejercicio'), ('Joyeria', 'Joyeria'), ('Sin clasificación', 'Sin clasificación')], default='Sin clasificación', max_length=20, null=True)),
                ('product_image', models.ImageField(default='productDefault.png', upload_to='')),
                ('STATE', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, null=True)),
                ('Product_type', models.CharField(choices=[('Singular', 'Singular'), ('PACK', 'PACK')], default='Singular', max_length=10, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('validation', models.BooleanField(default=False)),
                ('validation_date', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ProductCreated_by', to=settings.AUTH_USER_MODEL)),
                ('validation_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ProductValidated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
