# Generated by Django 4.0.5 on 2023-06-04 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_modifyproduct_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHILD_QUANTITY', models.PositiveIntegerField(default=0)),
                ('SKU_CHILD', models.ForeignKey(default=None, limit_choices_to=models.Q(('STATE', 'Activo'), ('Product_type', 'Singular')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singular_sku', to='tables.product')),
                ('SKU_PACK', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_sku', to='tables.product')),
            ],
        ),
    ]
