# Generated by Django 4.0.5 on 2023-06-04 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_packrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packrelation',
            name='SKU_CHILD',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('STATE', 'Activo'), ('Product_type', 'Singular'), ('validation', True)), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singular_sku', to='tables.product'),
        ),
    ]
