# Generated by Django 4.0.5 on 2023-07-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_packrelation_sku_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='deactivationproduct_request',
            name='additional_note',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
