# Generated by Django 4.0.5 on 2023-07-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_deactivationproduct_request_additional_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deactivationproduct_request',
            name='additional_note',
        ),
    ]
