# Generated by Django 4.0.5 on 2023-07-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_remove_deactivationproduct_request_additional_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='deactivationproduct_request',
            name='additional_note',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
