# Generated by Django 4.0.5 on 2023-07-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_restoreproduct_request_additional_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deactivationproduct_request',
            name='additional_note',
        ),
        migrations.RemoveField(
            model_name='restoreproduct_request',
            name='additional_note',
        ),
    ]
