# Generated by Django 4.0.5 on 2023-07-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_alter_modifyproduct_request_modified_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
