# Generated by Django 4.0.5 on 2023-07-23 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0016_alter_product_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifyproduct_request',
            name='modified_classification',
            field=models.CharField(choices=[('Elctrónica', 'Elctrónica'), ('Ejercicio', 'Ejercicio'), ('Press banca', 'Press banca'), ('Bicicletas', 'Bicicletas'), ('Mancuernas', 'Mancuernas'), ('Trotadoras', 'Trotadoras'), ('Joyeria', 'Joyeria'), ('Sin clasificación', 'Sin clasificación')], default='Sin clasificación', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modifyproduct_request',
            name='past_classification',
            field=models.CharField(choices=[('Elctrónica', 'Elctrónica'), ('Ejercicio', 'Ejercicio'), ('Press banca', 'Press banca'), ('Bicicletas', 'Bicicletas'), ('Mancuernas', 'Mancuernas'), ('Trotadoras', 'Trotadoras'), ('Joyeria', 'Joyeria'), ('Sin clasificación', 'Sin clasificación')], default='Sin clasificación', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='classification',
            field=models.CharField(choices=[('Elctrónica', 'Elctrónica'), ('Ejercicio', 'Ejercicio'), ('Press banca', 'Press banca'), ('Bicicletas', 'Bicicletas'), ('Mancuernas', 'Mancuernas'), ('Trotadoras', 'Trotadoras'), ('Joyeria', 'Joyeria'), ('Sin clasificación', 'Sin clasificación')], default='Sin clasificación', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='validation_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ProductValidated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='validation_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
