# Generated by Django 4.0.5 on 2023-05-17 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_image', models.ImageField(default='marketplaceDefault.png', upload_to='')),
                ('Marketplace_name', models.CharField(max_length=30, unique=True)),
                ('ESTADO', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('validation', models.BooleanField(default=False)),
                ('validation_date', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='MarketplaceCreated_by', to=settings.AUTH_USER_MODEL)),
                ('validation_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='MarketplaceValidated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
