# Generated by Django 4.0.5 on 2023-05-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplace',
            old_name='ESTADO',
            new_name='STATE',
        ),
    ]
