# Generated by Django 4.0.5 on 2023-05-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0004_restoremarketplace_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='referencial_description',
            field=models.CharField(default='Sin descripción', max_length=350),
        ),
    ]
