# Generated by Django 4.0.5 on 2023-05-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0006_modifymarketplace_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifymarketplace_request',
            old_name='marketplace_image',
            new_name='modified_marketplace_image',
        ),
        migrations.RenameField(
            model_name='modifymarketplace_request',
            old_name='referencial_description',
            new_name='modified_referencial_description',
        ),
        migrations.AddField(
            model_name='modifymarketplace_request',
            name='past_marketplace_image',
            field=models.ImageField(default='marketplaceDefault.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='modifymarketplace_request',
            name='past_referencial_description',
            field=models.CharField(default='Sin descripción', max_length=350),
        ),
    ]
