# Generated by Django 4.0.5 on 2023-05-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0008_alter_marketplace_referencial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifymarketplace_request',
            name='modified_referencial_description',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='modifymarketplace_request',
            name='past_referencial_description',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
