# Generated by Django 4.0.5 on 2023-05-19 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplaces', '0004_restoremarketplace_request'),
        ('tables', '0004_modifyproduct_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('gross_sales', models.IntegerField(default=0)),
                ('sale_number', models.CharField(max_length=40)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('commission', models.IntegerField(default=0)),
                ('shipping_cost', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('SKU', models.ForeignKey(default=None, limit_choices_to=models.Q(('ESTADO', 'Activo'), ('STOCK__gt', 0)), on_delete=django.db.models.deletion.CASCADE, to='tables.product', to_field='SKU')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='SaleCreated_by', to=settings.AUTH_USER_MODEL)),
                ('sale_marketplace', models.ForeignKey(limit_choices_to={'ESTADO': 'Activo'}, on_delete=django.db.models.deletion.CASCADE, to='marketplaces.marketplace', to_field='Marketplace_name')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation', models.BooleanField(default=False)),
                ('validation_date', models.DateTimeField(default=None, null=True)),
                ('Compared', models.BooleanField(default=False)),
                ('validation_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Sales_groupValidated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesGroup_SaleRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.sale')),
                ('id_Sales_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.sales_group')),
            ],
        ),
    ]
