# Generated by Django 4.0.5 on 2023-05-19 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0002_remove_sale_created_by_remove_sale_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_group',
            name='Compared_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Sales_groupCompared_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sales_group',
            name='Compared_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
