# Generated by Django 4.0.5 on 2023-05-19 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0004_restoremarketplace_request'),
        ('tables', '0004_modifyproduct_request'),
        ('Sales', '0003_sales_group_compared_by_sales_group_compared_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='SKU',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('STATE', 'Activo'), ('validation', True)), on_delete=django.db.models.deletion.CASCADE, to='tables.product', to_field='SKU'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_marketplace',
            field=models.ForeignKey(limit_choices_to=models.Q(('STATE', 'Activo'), ('validation', True)), on_delete=django.db.models.deletion.CASCADE, to='marketplaces.marketplace', to_field='Marketplace_name'),
        ),
    ]
