# Generated by Django 4.0.5 on 2023-05-19 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0004_alter_sale_sku_alter_sale_sale_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_group',
            name='Compared',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sales_group',
            name='Compared_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Sales_groupCompared_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sales_group',
            name='Compared_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sales_group',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='SaleCreated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sales_group',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sales_group',
            name='validation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sales_group',
            name='validation_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Sales_groupValidated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sales_group',
            name='validation_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
