# Generated by Django 4.0.5 on 2023-05-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_sales_group_compared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_group',
            name='Compared_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
