# Generated by Django 4.0.5 on 2023-06-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_sale_sale_group_delete_salesgroup_salerelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='Sale_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.sales_group'),
        ),
    ]
