# Generated by Django 4.0.5 on 2023-06-05 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0009_alter_modifymarketplace_request_modified_referencial_description_and_more'),
        ('Sales', '0010_alter_sale_sale_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_group',
            name='sale_marketplace',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('STATE', 'Activo'), ('validation', True)), on_delete=django.db.models.deletion.CASCADE, to='marketplaces.marketplace', to_field='Marketplace_name'),
        ),
    ]
