# Generated by Django 4.0.5 on 2023-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0014_alter_sale_sale_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='commission',
            field=models.IntegerField(default=0, verbose_name='Comision'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='gross_sales',
            field=models.IntegerField(default=0, verbose_name='Venta_bruta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(max_length=40, verbose_name='Numero_venta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shipping_cost',
            field=models.IntegerField(default=0, verbose_name='Costo_envio'),
        ),
    ]
