# Generated by Django 4.0.5 on 2023-06-06 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0015_alter_sale_commission_alter_sale_gross_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha_venta'),
        ),
    ]
