# Generated by Django 4.0.5 on 2023-06-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0017_alter_sale_commission_alter_sale_gross_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
