# Generated by Django 4.0.5 on 2023-06-23 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0018_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
