# Generated by Django 4.0.5 on 2023-06-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0020_alter_sale_sale_marketplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_marketplace',
        ),
    ]
