# Generated by Django 4.0.5 on 2023-07-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0021_remove_sale_sale_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_group',
            name='additional_note',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
